name: UpdateData

on:
  workflow_dispatch:
  schedule:
    # 2時間毎
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Setup Deno, Velociraptor
        uses: jurassiscripts/setup-velociraptor@v2

      - name: Update data
        run: vr update

      - name: Deno fmt
        run: vr fmt

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "add: new episode"
