name: UpdateData

on:
  schedule:
    # 1時間毎
    - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update data
        run: deno run --allow-net --allow-read --allow-write ./src/update.ts

      - name: Deno fmt
        run: deno fmt .

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
