name: UpdateData

on:
  schedule:
    # 2時間毎
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update data
        run: deno run --allow-env --allow-net --allow-read --allow-write ./src/main.ts

      - name: Deno fmt
        run: deno fmt ./docs/*

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "add: new episode"
